//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int ID { get; set; }
        public string MSSV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string MaLop { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<short> TrangThai { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
